repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: blue
        name: blue
        entry: blue .
        language: system
        types: [python]
        pass_filenames: false
